### ISSUE TITLE
Transaction contains data? false

### ISSUE THREAD

**Issue by fed-franz** [Tierion/blockchain-anchor#1]
Testing out the code in the Readme section, it gives me no errors but when it tests if the transaction contains data it output 'false'.
What am I doing wrong?

**Comment by jasonbukowski** [comment]
The sample code in the README serves to highlight the usage of each method, but does not necessarily contain valid transaction ids or data. Send some hex data to the embed method and you'll receive a transaction id where that data has been anchored. Run the confirm method with that transaction id and hex data, and you will receive a 'true' response.

**Comment by fed-franz** [comment]
Sorry, I didn't explain myself well.
Of course I didn't use the same transaction ID.
I did what you said, that is using the embed method followed by the confirm method using the received transaction (I merged the code into one script):

[first part is the same as the README]
`anchor.embed(hexData, function (err, result) {
  if(err) {
        console.log('error:'+err)
  } else {
    txId = result
        console.log('New transaction Id = ' + result);

```
anchor.confirm(txId, hexData, function (err, result) {
  if(err) {
      console.log('error:'+err);
  } else {
      console.log('Transaction contains data? ' + result);
  }
   });
}
```

});`

And this is what I get:
`$ node test.js 
New transaction Id = 4d1c810d9fdd5383dfcdd13c9c07ce6ce2821e12ab90f34c98eb3d26490d8d2e
Transaction contains data? false
`

**Comment by jasonbukowski** [comment]
Does the following code work for you? I confirmed it works on my end, using both main and testnet. I was also able to confirm your transaction '4d1c810d9fdd5383dfcdd13c9c07ce6ce2821e12ab90f34c98eb3d26490d8d2e' contains the data '05ae04314577b2783b4be98211d1b72476c59e9c413cfb2afa2f0c68e0d93911'. Are you still unable to do so?

```
var anchor = blockchainAnchor(yourprivateKeyWIFhere);
var hexData = '05ae04314577b2783b4be98211d1b72476c59e9c413cfb2afa2f0c68e0d93911';
anchor.embed(hexData, function (err, result) {
    if (err) {
        console.log('error:' + err);
    } else {
        var txId = result;
        console.log('New transaction Id = ' + result);

        anchor.confirm(txId, hexData, function (err, result) {
            if (err) {
                console.log('error:' + err);
            } else {
                console.log('Transaction contains data? ' + result);
            }
        });
    }
});
```

If you still have issues confirming, try setting the blockchainServiceName option to 'blockr' or 'insightbitpay' and see if that gives a different result.

**Comment by fed-franz** [comment]
If I use testnet I get this error:
`./node_modules/bitcoinjs-lib/src/ecpair.js:76
    if (version !== network.wif) throw new Error('Invalid network version')
                                 ^
Error: Invalid network version
`

With mainnet I can't try it out right now because I have no credit...

The strange thing is that I tried again to confirm transaction '4d1c810d9fdd5383dfcdd13c9c07ce6ce2821e12ab90f34c98eb3d26490d8d2e',
and still I get 'false'...

What code did you use to confirm that?

**Comment by jasonbukowski** [comment]
I confirmed it with the same confirm call included in the sample code I provided in my previous comment. How are you initializing the anchor object itself? For testnet, it should look something like this ->

`var anchor = blockchainAnchor(yourTestnetWIFhere, { useTestnet: true });`

**Comment by fed-franz** [comment]
With this code:
`var blockchainAnchor = require('blockchain-anchor');
var libBitcoinJs = require('bitcoinjs-lib');

var key = libBitcoinJs.ECPair.makeRandom();
var privateKeyWIF = key.toWIF();
console.log('WIF:'+privateKeyWIF);

var anchor = blockchainAnchor(privateKeyWIF, { useTestnet: true });

var hexData = '05ae04314577b2783b4be98211d1b72476c59e9c413cfb2afa2f0c68e0d93911';
var txId = '4d1c810d9fdd5383dfcdd13c9c07ce6ce2821e12ab90f34c98eb3d26490d8d2e';

anchor.confirm(txId, hexData, function (err, result) {
      if(err) {
        console.log('error:'+err);
      } else {
        console.log('Transaction contains data? ' + result);
      }
});`

I get the "Invalid network version" error.

I guess this is something not depending on you library.
Any hint?

**Comment by jasonbukowski** [comment]
I'm fairly sure that the problem here is that libBitcoinJs.ECPair.makeRandom(); and key.toWIF(); are generating mainnet keys, so that when you are using the generated WIF and setting useTestNet to true, you are getting the invalid network as you are attempting to use the test network with main network keys. You can confirm this by not setting useTestNet (it defaults to false)... doing so should instead give you a 0 balance error instead.

**Comment by fed-franz** [comment]
Exactly.
I suppose it's some kind of bug.
I will look for a solution. Thanks for your help anyway!

**Comment by jasonbukowski** [comment]
I don't think there's a bug in the key generation, just that it is generating mainnet keys, which wont work on testnet. 

I've created a demo testnet address and funded it with some tBTC from a faucet. Try with the WIF shown below, this should most certainly work for you...

```
var privateKeyWIFgen = '91zof5adYrQJrKNBVTxmCJSbnPjU18GC1D8aXuouv9VZgGquNna';

var anchor = blockchainAnchor(privateKeyWIFgen, { useTestnet: true });

var hexData = '05ae04314577b2783b4be98211d1b72476c59e9c413cfb2afa2f0c68e0d93911';
var txId = '4d1c810d9fdd5383dfcdd13c9c07ce6ce2821e12ab90f34c98eb3d26490d8d2e';

anchor.confirm(txId, hexData, function (err, result) {
    if (err) {
        console.log('error:' + err);
    } else {
        console.log('Transaction contains data? ' + result);
    }
});
```

**Comment by fed-franz** [comment]
Yes it does! (I finally see a 'true'! :)

Then I have to find a different function to generate testnet keys.

Still I don't understand why I can't confirm the transaction i created and you correctly confirmed!
Anyway, mine was just a very quick test. I maybe made some silly mistake I didn't notice.

Thanks again.
I'm sure you library will be very handful
